# Generated by Django 5.2.8 on 2025-11-10 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_precio_venta_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table=None,
        ),
    ]
