# Generated by Django 5.2.8 on 2025-11-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
